server:
  port: 9008

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root
  application:
     name: QUIZZER-AUTH
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
  #      max-file-threshold: 1KB
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    #hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.format_sql: true